# DATA PREPROCESSING IN STOCK PRICE PREDICTION

Name:Priyadharshani

Register No:21UAI068

In [1]:
#1.IMPORTING LIBRARIES
import numpy as np # numerical data
import pandas as pd #analyzing the data in dataframe and series

In [2]:
#2.iMPORTING DATASET
data=pd.read_csv("stock.csv")
data

Date        Open        High         Low       Close   Adj Close  \
0     29/06/2010   19.000000   25.000000   17.540001   23.889999   23.889999   
1     30/06/2010   25.790001   30.420000   23.299999   23.830000   23.830000   
2     01/07/2010   25.000000   25.920000   20.270000   21.959999   21.959999   
3     02/07/2010   23.000000   23.100000   18.709999   19.200001   19.200001   
4     06/07/2010   20.000000   20.000000   15.830000   16.110001   16.110001   
...          ...         ...         ...         ...         ...         ...   
2411  28/01/2020  568.489990  576.809998  558.080017  566.900024  566.900024   
2412  29/01/2020  575.690002  589.799988  567.429993  580.989990  580.989990   
2413  30/01/2020  632.419983  650.880005  618.000000  640.809998  640.809998   
2414  31/01/2020  640.000000  653.000000  632.520020  650.570007  650.570007   
2415  03/02/2020  673.690002  786.140015  673.520020  780.000000  780.000000   

          Volume  
0     18766300.0  
1     17187100.0  
2      8218800.0  
3      5139800.0  
4      6866900.0  
...          ...  
2411  11788500.0  
2412  17801500.0  
2413  29005700.0  
2414  15719300.0  
2415  47065000.0  

[2416 rows x 7 columns]

In [3]:
data.shape

(2416, 7)

In [5]:
#SEPARATE INDEPENDENT VALUES
x=data[['Date','Open','High','Low','Close']].values#data.iloc[:,:-1].values
x

array([['29/06/2010', 19.0, 25.0, 17.540001, 23.889999],
       ['30/06/2010', 25.790001, 30.42, 23.299999, 23.83],
       ['01/07/2010', 25.0, 25.92, 20.27, 21.959999],
       ...,
       ['30/01/2020', 632.419983, 650.880005, 618.0, 640.809998],
       ['31/01/2020', 640.0, 653.0, 632.52002, 650.570007],
       ['03/02/2020', 673.690002, 786.140015, 673.52002, 780.0]],
      dtype=object)

In [6]:
#DEPENDENT VALUES
y=data[['Adj Close','Volume']].values
y

array([[2.38899990e+01, 1.87663000e+07],
       [2.38300000e+01, 1.71871000e+07],
       [2.19599990e+01, 8.21880000e+06],
       ...,
       [6.40809998e+02, 2.90057000e+07],
       [6.50570007e+02, 1.57193000e+07],
       [7.80000000e+02, 4.70650000e+07]])

In [7]:
#Finding missing values
#Find and count the missing values in our dataset
print(data.isnull().sum())

Date          0
Open          4
High          6
Low          12
Close         5
Adj Close     8
Volume        8
dtype: int64


In [8]:
#drop missing value records- remaining rows are kept as its place
data.dropna(inplace=True)

In [9]:
data

Date        Open        High         Low       Close   Adj Close  \
0     29/06/2010   19.000000   25.000000   17.540001   23.889999   23.889999   
1     30/06/2010   25.790001   30.420000   23.299999   23.830000   23.830000   
2     01/07/2010   25.000000   25.920000   20.270000   21.959999   21.959999   
3     02/07/2010   23.000000   23.100000   18.709999   19.200001   19.200001   
4     06/07/2010   20.000000   20.000000   15.830000   16.110001   16.110001   
...          ...         ...         ...         ...         ...         ...   
2411  28/01/2020  568.489990  576.809998  558.080017  566.900024  566.900024   
2412  29/01/2020  575.690002  589.799988  567.429993  580.989990  580.989990   
2413  30/01/2020  632.419983  650.880005  618.000000  640.809998  640.809998   
2414  31/01/2020  640.000000  653.000000  632.520020  650.570007  650.570007   
2415  03/02/2020  673.690002  786.140015  673.520020  780.000000  780.000000   

          Volume  
0     18766300.0  
1     17187100.0  
2      8218800.0  
3      5139800.0  
4      6866900.0  
...          ...  
2411  11788500.0  
2412  17801500.0  
2413  29005700.0  
2414  15719300.0  
2415  47065000.0  

[2377 rows x 7 columns]

In [10]:

#simple imputer-filled missing values in numerical
from sklearn.impute import SimpleImputer

In [11]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [12]:
# Fit- we split our data into training and testing adjusts weights according to data values for better accuracy
imputer=imputer.fit(x[:,1:3])

In [13]:
#transform calculate the mean value
x[:,1:3]=imputer.transform(x[:,1:3])
x

array([['29/06/2010', 19.0, 25.0, 17.540001, 23.889999],
       ['30/06/2010', 25.790001, 30.42, 23.299999, 23.83],
       ['01/07/2010', 25.0, 25.92, 20.27, 21.959999],
       ...,
       ['30/01/2020', 632.419983, 650.880005, 618.0, 640.809998],
       ['31/01/2020', 640.0, 653.0, 632.52002, 650.570007],
       ['03/02/2020', 673.690002, 786.140015, 673.52002, 780.0]],
      dtype=object)

In [14]:
#4.ENCODING CATEGORICAL VALUES Label encoder- each unique values it gives an index like 1,2,3
#One hot encoder- take an each index value to add one feature
from sklearn.preprocessing import LabelEncoder

In [15]:
label_encode_x=LabelEncoder()
label_encode_y=LabelEncoder()

In [16]:
x[:,0]=label_encode_x.fit_transform(x[:,0])
x

array([[2246, 19.0, 25.0, 17.540001, 23.889999],
       [2319, 25.790001, 30.42, 23.299999, 23.83],
       [33, 25.0, 25.92, 20.27, 21.959999],
       ...,
       [2301, 632.419983, 650.880005, 618.0, 640.809998],
       [2374, 640.0, 653.0, 632.52002, 650.570007],
       [166, 673.690002, 786.140015, 673.52002, 780.0]], dtype=object)

In [17]:
label_encode_x.classes_

array(['01/02/2011', '01/02/2012', '01/02/2013', ..., '31/12/2015',
       '31/12/2018', '31/12/2019'], dtype=object)

In [28]:
#SPLITTING DATASET INTO TRAINING AND TESTING
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1)

In [23]:
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[42 135.0 136.520004 132.630005 135.550003]
 [1312 217.809998 219.990005 214.5 215.470001]
 [569 260.5 260.820007 248.020004 250.070007]
 ...
 [292 240.490005 242.350006 236.529999 238.929993]
 [185 29.950001 31.5 29.5 30.129999]
 [1252 255.149994 262.459991 252.419998 260.73999]]
[[756 29.309999 29.940001 29.309999 29.940001]
 [1446 241.389999 241.550003 233.509995 235.839996]
 [928 364.48999 368.76001 360.399994 362.75]
 ...
 [1365 172.419998 172.949997 164.770004 166.770004]
 [907 222.949997 223.380005 209.0 209.259995]
 [2339 229.149994 232.440002 224.210007 225.610001]]
[[1.35550003e+02 5.32360000e+06]
 [2.15470001e+02 3.11260000e+06]
 [2.50070007e+02 7.36390000e+06]
 ...
 [2.38929993e+02 3.68260000e+06]
 [3.01299990e+01 6.20920000e+06]
 [2.60739990e+02 8.30010000e+06]]
[[2.99400010e+01 7.07400000e+05]
 [2.35839996e+02 5.07130000e+06]
 [3.62750000e+02 5.97290000e+06]
 ...
 [1.66770004e+02 3.88760000e+06]
 [2.09259995e+02 1.51862000e+07]
 [2.25610001e+02 9.32060000e+06]]


In [24]:
#6.FEATURE SCALING
from sklearn.preprocessing import StandardScaler

In [25]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
print(x_train)
print(x_test)

[[-1.67458618 -0.43190346 -0.44104486 -0.43364246 -0.42857201]
 [ 0.14730613  0.27027887  0.25728995  0.27101703  0.24958074]
 [-0.9185726   0.63226614  0.59888588  0.55952552  0.54317546]
 ...
 [-1.31594596  0.46259261  0.44436036  0.46063043  0.44864804]
 [-1.46944397 -1.32266853 -1.3196734  -1.321288   -1.32310239]
 [ 0.06123247  0.58690109  0.61260647  0.59739651  0.63371448]]
[[-0.63858959 -1.3145429  -1.30810361 -1.30839941 -1.29635215]
 [ 0.34924923  0.44320781  0.40647138  0.41249486  0.39384962]
 [-0.39234571  1.46347893  1.43719344  1.48185958  1.43563456]
 ...
 [ 0.23328555 -0.12842586 -0.14936177 -0.16681101 -0.17313545]
 [-0.42241037  0.29037432  0.25924855  0.20593702  0.17565843]
 [ 1.6277131   0.34176082  0.33265738  0.33411926  0.30987315]]
